In [13]:
from numpy import *
arr=array([1,2,3,4,5])#it is 1 dimensional array
b=array([[1,2,3],[4,5,6]])# 2 dim array
c=array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])# 3 dim array
print(f"one dim array is :{arr}")
print(f"twp dim array is :{b}")
print(f"three dim array is :{c}")

one dim array is :[1 2 3 4 5]
twp dim array is :[[1 2 3]
 [4 5 6]]
three dim array is :[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
#numpy version

print(numpy.__version__)


1.19.2


In [10]:
arr=array(42)
print(arr)
print(arr.ndim) #show the dimensions of the array

0


In [24]:
from numpy import *
arr=array([[1,2,3,4,5],[5,6,7,8]],ndmin=5)
print(arr)
print(arr.ndim)
print(arr.dtype)

[[[[[list([1, 2, 3, 4, 5]) list([5, 6, 7, 8])]]]]]
5
object


<ipython-input-24-3d18132ea449>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr=array([[1,2,3,4,5],[5,6,7,8]],ndmin=5)


In [27]:
arr=array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element in 1st dim is :",arr[0,1])
print(arr[0][1])

2nd element in 1st dim is : 2
2


In [28]:
#one dimensional array slicing
arr=array([1,2,3,4,5,6,7,8])
print(arr[4:])

[5 6 7 8]


In [43]:
#2 dimensional array slicing
arr=array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1:])
# or print(arr[1][1:])
print(arr[0:2,1])
# or print([arr[0][1],arr[1][1]])


[6 7 8]
[6 7 8]
[2 6]
[2, 6]


In [47]:
arr=array([1,2,3,4])
print(arr.dtype)# find the data type of the array

int32


In [48]:
fruits=array(["apple","orange","grapes"])
print(fruits.dtype)#output is u6(unicode string)

<U6


In [58]:
arr=array([1,2,3,4])
print(arr.dtype)

arr=array([1,2,3,4],dtype='i8')#it indicate integer with 8 byte datatype  (8 byte =64 bit).hence the ans is int64
print(arr)
print(arr.dtype)

int32
[1 2 3 4]
int64


In [56]:
arY=array([1,2,3,4,5],dtype='S')
print(arY)
print(arY.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [61]:
arr=array([1.1,2.2,3.3])
print(arr)

print(arr.dtype)
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)




[1.1 2.2 3.3]
float64
[1 2 3]
int32


In [62]:
#diff b/w copy and view 
#copy

arr=array([1,2,3,4])
x=arr.copy()
print(x)
arr[0]=42
print(arr)
print(x)#changes in original does not affect the duplicate array


[1 2 3 4]
[42  2  3  4]
[1 2 3 4]


In [65]:
#view
arr=array([1,2,3,4,5])
print(arr)
x=arr.view()
arr[0]=42
print(arr)#changes in original array also affect the duplicate array too
print(x)

[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [66]:
arr=array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [72]:
#reshaping
arr=array([[1,2,3,4],[2,3,4,5]])
print(arr.shape)
print(arr.reshape(1,8))#reshape to the given number

(2, 4)
[[1]
 [2]
 [3]
 [4]
 [2]
 [3]
 [4]
 [5]]


In [74]:
arr=array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [75]:
#for loop
arr=array([[1,2,3,4,5],[5,6,7,8,9]])
for i in arr:
    print(i)

[1 2 3 4 5]
[5 6 7 8 9]


In [76]:
arr=array([[1,2,3,4,5],[5,6,7,8,9]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
5
6
7
8
9


In [79]:
#concatenate
arr=array([1,2,3,4,5])
arr2=array([6,7,8,9,10])
print(concatenate((arr,arr2)))

[ 1  2  3  4  5  6  7  8  9 10]


In [80]:
#statcking (hstack,vstack and dstack)
#HORIZONTAL STACK
arr=array([1,2,3])
arr2=array([4,5,6])
x=hstack((arr,arr2))
print(x)

[1 2 3 4 5 6]


In [81]:
#VERTICAL STACK
arr=array([1,2,3])
arr2=array([4,5,6])
y=vstack((arr,arr2))
print(y)

[[1 2 3]
 [4 5 6]]


In [82]:
#depth stack
arr=array([1,2,3])
arr2=array([4,5,6])
z=dstack((arr,arr2))
print(z)

[[[1 4]
  [2 5]
  [3 6]]]


In [86]:
#exception
arr=array([1,2,3])
arr2=array([4,5,6])
print(list(map(lambda x,y:[x,y],arr,arr2)))

[[1, 4], [2, 5], [3, 6]]


In [88]:
#array spliting
arr=array([1,2,3,4,5,6,7,8])
print(array_split(arr,4))
print(array_split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


TypeError: Field elements must be 2- or 3-tuples, got '6'

In [94]:
arr=array([1,2,3,4,5,6,7,8])
newarr=array_split(arr,2)
print(newarr[0],newarr[1])

[1 2 3 4] [5 6 7 8]


In [98]:
arr=array([[1,2,3,4,5],[6,7,8,9,10]])
newarr=array_split(arr,4)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([], shape=(0, 5), dtype=int32), array([], shape=(0, 5), dtype=int32)]
[[1 2 3 4 5]]
[[ 6  7  8  9 10]]
[]
[]


In [110]:
arr=array([1,2,3,4,5,6,7,8])
newarr=numpy.split(arr,2)
print(newarr)
nr=numpy.hsplit(arr,2)
print(nr)


[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
